### ISSUE TITLE
Training process?

### ISSUE THREAD

**Issue by fmac2000** [ZhangXInFD/SpeechTokenizer#2]
Hi Authors,

This paper is so unbelievably useful for my research - thank you, what a great idea and paper this is!
I'm looking through the code to learn about this modification to the quantizer allowing for it to learn semantic distillation after the first RVQ pass with help from Hubert, but, it seems the model uploaded is just encodec? I can't find the correct snippet nor can piece together how one may train this.

Thank you

**Comment by ZhangXInFD** [comment]
Thank you for your attention！In terms of inference, our model is identical to EnCodec and does not incorporate HuBERT's distillation process. The training details are detailed in paper. At this stage, we plan to open-source only the inference code and checkpoint.

**Comment by lifeiteng** [comment]
@ZhangXInFD 我试图训练模型，但没有训出合理的结果，RVQ1 重建仍然带有较多的说话人信息。

1. 我修正了 https://arxiv.org/abs/2308.16692 distill 公式的错误，加了负号
2. HuBERT 的 checkpoint 用的具体是哪一个？

**Comment by ZhangXInFD** [comment]
@lifeiteng 
不好意思，论文的公式给的有一点问题，distill loss应该是沿特征维度方向计算而不是计算时序上每一步的特征间的相似度损失。公式和分析实验如下，我们之前已上传新的版本到arxiv上但目前arxiv还未帮我们更新。
<img width="509" alt="image" src="https://github.com/ZhangXInFD/SpeechTokenizer/assets/60635267/b6e80092-9332-46fa-8344-0788fdb93831">
<img width="518" alt="image" src="https://github.com/ZhangXInFD/SpeechTokenizer/assets/60635267/c385171c-f715-46db-97b7-dd0996de1827">

**Comment by lifeiteng** [comment]
@ZhangXInFD 

D-Axis 看起来效果好很多。

还有一个问题，我看开放的代码里的 forward 用了全部 n_q，训练的时候也是这么做的吗？

方便加我微信聊下么 Feiteng17

**Comment by ZhangXInFD** [comment]
@lifeiteng 训练的时候蒸馏只用了rvq-1也就是n_q=0,重建任务用了全部的n_q，源代码的foward里返回的feature即rvq1返回的quantized值

**Comment by TechInterMezzo** [comment]
Is there a chance that you would publish the training code in the future or did you already decide gainst that?

**Comment by ZhangXInFD** [comment]
@TechInterMezzo We will pulish the training code at the end of this year or early next year. The projection matrix A is actually a linear layer (https://github.com/ZhangXInFD/SpeechTokenizer/blob/adc2c3fc65a2eb82efb4744b66905ed018d5895a/speechtokenizer/model.py#L37C1-L40C43), used to align dimensions between RVQ-1 codewords and HuBERT representations.

**Comment by UkiTenzai** [comment]
> @ZhangXInFD
> 
> D-Axis 看起来效果好很多。
> 
> 还有一个问题，我看开放的代码里的 forward 用了全部 n_q，训练的时候也是这么做的吗？
> 
> 方便加我微信聊下么 Feiteng17

请问一般情况下 蒸馏损失的数值是多少呢？是前几次迭代就降到0.36左右，后面不变了吗
